---


- name: Apply for common configuration to all the nodes
  hosts: 127.0.0.1
  remote_user: root

  #roles:
   #- common
   
- name: deploy MySQL and configure databases
  hosts: 127.0.0.1
  remote_user: root
  become: true
  become_method: sudo su
  become_user: root
   
  roles:
   - db
   
- name: deploy Apache, PHP and configure website code
  hosts: 127.0.0.1
  remote_user: root
  become: true
  become_method: sudo su
  become_user: root
  
  roles:
   - web
